In [ ]:
#| default_exp embedding_ex

In [ ]:
#| exporti

from fhemb.embedding import EmbeddingCollection

DEBUG:fhemb.config.settings:Loading environment from /Users/radned/.config/fhemb/.env.paths
DEBUG:fhemb.config.settings:Loading environment from /Users/radned/.config/fhemb/.env.db

In [ ]:
#| exports

from nbdev_fhemb.datasource_ex import dg0, pca

 [DEBUG] mixins.wrapper: wrapper of process_subjects called with subjs=[(40, 42), 50, (65, 68)], args=() and kwargs={'title': 'Don Giovanni', 'time_interval': (14200, 15200)}
 [DEBUG] mixins.wrapper: Calling: get_piece_attribute_values with title=Don Giovanni and atributes=['number_of_subjects']
 [DEBUG] mixins.wrapper: to get subjects_int from 'number_of_subjects' record in performance_library
 [DEBUG] mixins.wrapper: Calling: __init__ with subjs=[40, 41, 42, 50, 65, 66, 67, 68] and args=() and kwargs={'title': 'Don Giovanni', 'time_interval': (14200, 15200)}
 [DEBUG] piece.__init__: Processed subjects: [40, 41, 42, 50, 65, 66, 67, 68]
 [DEBUG] piece.__init__: Compact numeric subjects: [(40, 42), 50, (65, 68)]

# Create Complex Embeddings
> by constructing an `EmbeddingCollection` object

There are two routes to construct an `EmbeddingCollection` object. One is to use the `EmbeddingCollection` constructor, and the other is to use the `Datasource.projection` syntactic shorthand. We demonstrate both: first constructing *full embeddings*, i.e., without using projection, then constructing the more general *projected embeddings*.

## Full Embeddings
> no features are projected out

In [ ]:
#| exports
#| eval: false

pca_emb = dg0.face_t.create_pca_embedding(   # embed into principal components
    factory=pca                              # specify PCA factory to use for creating the PCA embedding (imported)
)[0]                                         # the function 'create_pca_embedding' return a tuple (Embedding, ...)

percentile_emb = dg0.face_t.percentiles_ts   # embed into percentiles  

bin_emb = dg0.face_t.binheights_ts           # embed into bin heights

 [INFO] piece._load_from_db: Loading face_t from the database
 [INFO] piece._fetch_from_DB: Fetching data by query SELECT subj40, subj41, subj42, subj50, subj65, subj66, subj67, subj68 FROM dg.faceposition_t WHERE frame_number >= 14200 AND frame_number < 15200 ORDER BY frame_number
/Users/radned/.pyenv/versions/p311.fhemb/lib/python3.11/site-packages/paramiko/pkey.py:82: CryptographyDeprecationWarning: TripleDES has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.TripleDES and will be removed from cryptography.hazmat.primitives.ciphers.algorithms in 48.0.0.
  "cipher": algorithms.TripleDES,
/Users/radned/.pyenv/versions/p311.fhemb/lib/python3.11/site-packages/paramiko/transport.py:253: CryptographyDeprecationWarning: TripleDES has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.TripleDES and will be removed from cryptography.hazmat.primitives.ciphers.algorithms in 48.0.0.
  "class": algorithms.TripleDES,
 [DEBUG] piece.start: SSH tunnel established
 [DEBUG] piece.start: Effective DB params after start: dbname=tcamera user=tanalyst host=127.0.0.1 port=53509
 [DEBUG] dbms.__enter__: Database connection opened: True (conn.closed=0)
 [DEBUG] dbms.__enter__: Database cursor opened: True
 [INFO] dbms.data_query: Fetching time series of ['subj40', 'subj41', 'subj42', 'subj50', 'subj65', 'subj66', 'subj67', 'subj68']
 [DEBUG] dbms.__exit__: __exit__ called with exc_type=None,
exc_val=None,
exc_tb=None
 [DEBUG] dbms.__exit__: Cursor closed: True
 [DEBUG] dbms.__exit__: Transaction committed
 [DEBUG] dbms.__exit__: Connection closed: True (conn.closed = 1)
 [INFO] piece.fetch_timeseries: 1000 rows fetched successfully!
 [DEBUG] piece.stop: SSH tunnel closed
 [INFO] piece._fetch_from_DB: Fetching data by query SELECT subj40, subj41, subj42, subj50, subj65, subj66, subj67, subj68 FROM dg.face_t WHERE frame_number >= 14200 AND frame_number < 15200 ORDER BY frame_number
 [DEBUG] piece.start: SSH tunnel established
 [DEBUG] piece.start: Effective DB params after start: dbname=tcamera user=tanalyst host=127.0.0.1 port=53578
 [DEBUG] dbms.__enter__: Database connection opened: True (conn.closed=0)
 [DEBUG] dbms.__enter__: Database cursor opened: True
 [INFO] dbms.data_query: Fetching time series of ['subj40', 'subj41', 'subj42', 'subj50', 'subj65', 'subj66', 'subj67', 'subj68']
 [DEBUG] dbms.__exit__: __exit__ called with exc_type=None,
exc_val=None,
exc_tb=None
 [DEBUG] dbms.__exit__: Cursor closed: True
 [DEBUG] dbms.__exit__: Transaction committed
 [DEBUG] dbms.__exit__: Connection closed: True (conn.closed = 1)
 [INFO] piece.fetch_timeseries: 1000 rows fetched successfully!
 [DEBUG] piece.stop: SSH tunnel closed
 [DEBUG] piece.__init__: Creating a Mixints with time_interval=(14200, 15200), subjects=None
 [DEBUG] piece.__init__: Subjects: ['subj40', 'subj41', 'subj42', 'subj50', 'subj65', 'subj66', 'subj67', 'subj68']
 [DEBUG] embedding.__init__: Creating a BaseEmbedding with time_interval=(14200, 15200), subjects=None
 [DEBUG] embedding.__init__: Subjects: ['subj40', 'subj41', 'subj42', 'subj50', 'subj65', 'subj66', 'subj67', 'subj68']
 [DEBUG] embedding.__init__: No features provided, using all features from the first subject prefixed with fp
 [DEBUG] piece.__init__: Creating a Generalts with time_interval=(14200, 15200), subjects=None
 [DEBUG] piece.create_pca_embedding: Calling create_pca_embedding
 [DEBUG] tutils.create: Creating create_pca_embedding with args: StandardScaler(copy=True,with_mean=True,with_std=False) | KernelPCA(alpha=1.0,coef0=1,copy_X=True,degree=3,eigen_solver='auto',fit_inverse_transform=True,gamma=0.07,iterated_power='auto',kernel='sigmoid',kernel_params=None,max_iter=None,n_components=5,n_jobs=None,random_state=None,remove_zero_eig=False,tol=0) and kwargs: dict_keys(['factory', 'datasource', 'subjects', 'time_interval', 'temperature_threshold'])
 [DEBUG] tutils.create: Calculating create_pca_embedding for StandardScaler(copy=True,with_mean=True,with_std=False) | KernelPCA(alpha=1.0,coef0=1,copy_X=True,degree=3,eigen_solver='auto',fit_inverse_transform=True,gamma=0.07,iterated_power='auto',kernel='sigmoid',kernel_params=None,max_iter=None,n_components=5,n_jobs=None,random_state=None,remove_zero_eig=False,tol=0)
 [DEBUG] factories.fit_pipe: Fitting PCA on data with shapes: [(1000, 244), (1000, 339), (1000, 279), (1000, 332), (1000, 454), (1000, 498), (1000, 374), (1000, 340)]
 [DEBUG] factories.fit_pipe: Intersection masks with shapes: [(21, 13), (22, 20), (23, 18), (28, 17), (30, 20), (32, 19), (27, 21), (24, 21)]
 [INFO] factories.fit_pipe: Pipeline cache key: StandardScaler(copy=True,with_mean=True,with_std=False) | KernelPCA(alpha=1.0,coef0=1,copy_X=True,degree=3,eigen_solver='auto',fit_inverse_transform=True,gamma=0.07,iterated_power='auto',kernel='sigmoid',kernel_params=None,max_iter=None,n_components=5,n_jobs=None,random_state=None,remove_zero_eig=False,tol=0)
 [DEBUG] factories.create_pca_embedding: Embedding shape for subject subj40: (5, 1000)
 [DEBUG] factories.create_pca_embedding: Embedding shape for subject subj41: (5, 1000)
 [DEBUG] factories.create_pca_embedding: Embedding shape for subject subj42: (5, 1000)
 [DEBUG] factories.create_pca_embedding: Embedding shape for subject subj50: (5, 1000)
 [DEBUG] factories.create_pca_embedding: Embedding shape for subject subj65: (5, 1000)
 [DEBUG] factories.create_pca_embedding: Embedding shape for subject subj66: (5, 1000)
 [DEBUG] factories.create_pca_embedding: Embedding shape for subject subj67: (5, 1000)
 [DEBUG] factories.create_pca_embedding: Embedding shape for subject subj68: (5, 1000)
 [DEBUG] factories.calc_eigenface_dictionary: Eigenfaces shape for subject subj40: (21, 13)
 [DEBUG] factories.calc_eigenface_dictionary: Eigenfaces shape for subject subj41: (22, 20)
 [DEBUG] factories.calc_eigenface_dictionary: Eigenfaces shape for subject subj42: (23, 18)
 [DEBUG] factories.calc_eigenface_dictionary: Eigenfaces shape for subject subj50: (28, 17)
 [DEBUG] factories.calc_eigenface_dictionary: Eigenfaces shape for subject subj65: (30, 20)
 [DEBUG] factories.calc_eigenface_dictionary: Eigenfaces shape for subject subj66: (32, 19)
 [DEBUG] factories.calc_eigenface_dictionary: Eigenfaces shape for subject subj67: (27, 21)
 [DEBUG] factories.calc_eigenface_dictionary: Eigenfaces shape for subject subj68: (24, 21)
 [INFO] factories.create_pca_embedding: Creating PCA embedding with cache key: StandardScaler(copy=True,with_mean=True,with_std=False) | KernelPCA(alpha=1.0,coef0=1,copy_X=True,degree=3,eigen_solver='auto',fit_inverse_transform=True,gamma=0.07,iterated_power='auto',kernel='sigmoid',kernel_params=None,max_iter=None,n_components=5,n_jobs=None,random_state=None,remove_zero_eig=False,tol=0)
 [DEBUG] embedding.__init__: Creating a BaseEmbedding with time_interval=(14200, 15200), subjects=['subj40', 'subj41', 'subj42', 'subj50', 'subj65', 'subj66', 'subj67', 'subj68']
 [DEBUG] embedding.__init__: Subjects: ['subj40', 'subj41', 'subj42', 'subj50', 'subj65', 'subj66', 'subj67', 'subj68']
 [DEBUG] embedding.__init__: Features setted explicitely: ['pc0', 'pc1', 'pc2', 'pc3', 'pc4']
 [INFO] piece._derive_features: Deriving binheights_ts, binedges, percentiles_ts, and features_ts
 [DEBUG] piece._cache_derived_features: Creating binhieghts_ts Embedding
 [DEBUG] embedding.__init__: Creating a BaseEmbedding with time_interval=(14200, 15200), subjects=None
 [DEBUG] embedding.__init__: Subjects: ['subj40', 'subj41', 'subj42', 'subj50', 'subj65', 'subj66', 'subj67', 'subj68']
 [DEBUG] embedding.__init__: No features provided, using all features from the first subject prefixed with bh
 [DEBUG] piece._cache_derived_features: Creating binedges
 [DEBUG] piece._cache_derived_features: Creating percentiles_ts Embedding
 [DEBUG] embedding.__init__: Creating a BaseEmbedding with time_interval=(14200, 15200), subjects=None
 [DEBUG] embedding.__init__: Subjects: ['subj40', 'subj41', 'subj42', 'subj50', 'subj65', 'subj66', 'subj67', 'subj68']
 [DEBUG] embedding.__init__: No features provided, using all features from the first subject prefixed with p
 [DEBUG] piece._cache_derived_features: Creating features_ts Embedding
 [DEBUG] embedding.__init__: Creating a BaseEmbedding with time_interval=(14200, 15200), subjects=None
 [DEBUG] embedding.__init__: Subjects: ['subj40', 'subj41', 'subj42', 'subj50', 'subj65', 'subj66', 'subj67', 'subj68']
 [DEBUG] embedding.__init__: Features setted explicitely: ['max', 'min', 'mean', 'variance', 'std', 'median', 'skew', 'kurtosis', 'entropy']
 [INFO] piece._derive_tracked: Deriving rsfacebbox_t and facesizes_t
 [DEBUG] piece.__init__: Creating a Mixints with time_interval=(14200, 15200), subjects=None
 [DEBUG] piece.__init__: Subjects: ['subj40', 'subj41', 'subj42', 'subj50', 'subj65', 'subj66', 'subj67', 'subj68']
 [DEBUG] embedding.__init__: Creating a BaseEmbedding with time_interval=(14200, 15200), subjects=None
 [DEBUG] embedding.__init__: Subjects: ['subj40', 'subj41', 'subj42', 'subj50', 'subj65', 'subj66', 'subj67', 'subj68']
 [DEBUG] embedding.__init__: No features provided, and features_tint does not have a features dimension, using None

### Combine full embeddings

#### `EmbeddingCollection` constructor

In [ ]:
#| exports
#| eval: false

combined_emb0 = EmbeddingCollection(pca_emb, percentile_emb, bin_emb)

#### `Datasource.project` syntactic shorthand

In [ ]:
#| exports
#| eval: false

combined_emb1 = dg0.face_t.project(                              # project all available features of the Datasource face_t to specified `features`
    features=[('pc0', 'pc4'), ('p0', 'p100'), ('bh0', 'bh18')],  # specify all features: none will be projected out
    pcfactory=pca,                                               # specify PCA for principle components 
)

 [DEBUG] piece.project: Calling BaseDatasource.project with subjs=all, features=[('pc0', 'pc4'), ('p0', 'p100'), ('bh0', 'bh18')], heatmap=None, fvector=None, fbands=None, pcfactory=<fhemb.utils.factories.ConcretePcaFactory object>, wdfactory=None
 [DEBUG] piece._choose_embedding: Classified features: {'percentiles': [('p0', 'p100')], 'bins': [('bh0', 'bh18')], 'pcomponents': [('pc0', 'pc4')], 'stat_features': []}
 [DEBUG] piece._choose_embedding: classified percentiles: [('p0', 'p100')]
 [DEBUG] piece._choose_embedding: classified bins: [('bh0', 'bh18')]
 [DEBUG] piece._choose_embedding: classified pcomponents: [('pc0', 'pc4')]
 [DEBUG] piece.create_pca_embedding: Calling create_pca_embedding
 [DEBUG] tutils.create: Creating create_pca_embedding with args: StandardScaler(copy=True,with_mean=True,with_std=False) | KernelPCA(alpha=1.0,coef0=1,copy_X=True,degree=3,eigen_solver='auto',fit_inverse_transform=True,gamma=0.07,iterated_power='auto',kernel='sigmoid',kernel_params=None,max_iter=None,n_components=5,n_jobs=None,random_state=None,remove_zero_eig=False,tol=0) and kwargs: dict_keys(['factory', 'datasource', 'subjects', 'time_interval', 'temperature_threshold'])
 [DEBUG] tutils.create: Using already calculated value for StandardScaler(copy=True,with_mean=True,with_std=False) | KernelPCA(alpha=1.0,coef0=1,copy_X=True,degree=3,eigen_solver='auto',fit_inverse_transform=True,gamma=0.07,iterated_power='auto',kernel='sigmoid',kernel_params=None,max_iter=None,n_components=5,n_jobs=None,random_state=None,remove_zero_eig=False,tol=0)
 [DEBUG] piece.project: Chosen embeddings: [('percentiles_ts', {'embedding': <fhemb.embedding.Embedding object>, 'features': [('p0', 'p100')]}), ('binheights_ts', {'embedding': <fhemb.embedding.Embedding object>, 'features': [('bh0', 'bh18')]}), ('pcomponents_ts', {'embedding': <fhemb.embedding.Embedding object>, 'features': [('pc0', 'pc4')]})]
 [DEBUG] embedding.project: Calling project for subjects=all and features=[('p0', 'p100')], heatmap=None, fvector=None, fbands=[], factory=None
 [DEBUG] mixins.wrapper: Calling _create_projection with stacklevel=2
 [DEBUG] mixins.wrapper: wrapper of process_subjects called with subjs=all, args=() and kwargs={'features': [('p0', 'p100')]}
 [DEBUG] mixins.wrapper: Getting subjects_int from self.subjects: ['subj40', 'subj41', 'subj42', 'subj50', 'subj65', 'subj66', 'subj67', 'subj68']
 [DEBUG] mixins.wrapper: Taking all subjects: [40, 41, 42, 50, 65, 66, 67, 68]
 [DEBUG] mixins.wrapper: Calling: _create_projection with subjs=[40, 41, 42, 50, 65, 66, 67, 68] and args=() and kwargs={'features': [('p0', 'p100')]}
 [DEBUG] mixins.wrapper: Calling _create_projection with subjs=[40, 41, 42, 50, 65, 66, 67, 68] and args=() and kwargs={'features': [('p0', 'p100')]}
 [DEBUG] mixins.wrapper: Processing features [('p0', 'p100')], heatmap None, fvector None, args=(['subj40', 'subj41', 'subj42', 'subj50', 'subj65', 'subj66', 'subj67', 'subj68'],), and kwargs={}
 [DEBUG] mixins.wrapper: Percentile features detected, after preprocessing: [(0, 20)]
 [DEBUG] mixins.wrapper: Validating feature: [(0, 20)]
 [DEBUG] mixins.validate_grid: Vallidating grid: [(0, 20)] and maxsize: 21
 [DEBUG] mixins.validate_grid: Vallidated grid: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
 [DEBUG] mixins.wrapper: valid_feature: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
 [DEBUG] mixins.wrapper: valid_features=[(0, 20)]
 [DEBUG] embedding._create_projection: Calling _create_projection for subjects=['subj40', 'subj41', 'subj42', 'subj50', 'subj65', 'subj66', 'subj67', 'subj68'], features=('p0', 'p5', 'p10', 'p15', 'p20', 'p25', 'p30', 'p35', 'p40', 'p45', 'p50', 'p55', 'p60', 'p65', 'p70', 'p75', 'p80', 'p85', 'p90', 'p95', 'p100'), and kwargs={'features_int': (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20)}
 [DEBUG] embedding.clone: Setting subjects_int to [40, 41, 42, 50, 65, 66, 67, 68]
 [DEBUG] embedding.project: Calling project for subjects=all and features=[('bh0', 'bh18')], heatmap=None, fvector=None, fbands=[], factory=None
 [DEBUG] mixins.wrapper: Calling _create_projection with stacklevel=2
 [DEBUG] mixins.wrapper: wrapper of process_subjects called with subjs=all, args=() and kwargs={'features': [('bh0', 'bh18')]}
 [DEBUG] mixins.wrapper: Getting subjects_int from self.subjects: ['subj40', 'subj41', 'subj42', 'subj50', 'subj65', 'subj66', 'subj67', 'subj68']
 [DEBUG] mixins.wrapper: Taking all subjects: [40, 41, 42, 50, 65, 66, 67, 68]
 [DEBUG] mixins.wrapper: Calling: _create_projection with subjs=[40, 41, 42, 50, 65, 66, 67, 68] and args=() and kwargs={'features': [('bh0', 'bh18')]}
 [DEBUG] mixins.wrapper: Calling _create_projection with subjs=[40, 41, 42, 50, 65, 66, 67, 68] and args=() and kwargs={'features': [('bh0', 'bh18')]}
 [DEBUG] mixins.wrapper: Processing features [('bh0', 'bh18')], heatmap None, fvector None, args=(['subj40', 'subj41', 'subj42', 'subj50', 'subj65', 'subj66', 'subj67', 'subj68'],), and kwargs={}
 [DEBUG] mixins.wrapper: Binheight features detected, features: [(0, 18)]
 [DEBUG] mixins.wrapper: Validating feature: [(0, 18)]
 [DEBUG] mixins.validate_grid: Vallidating grid: [(0, 18)] and maxsize: 19
 [DEBUG] mixins.validate_grid: Vallidated grid: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18]
 [DEBUG] mixins.wrapper: valid_feature: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18]
 [DEBUG] mixins.wrapper: valid_features=[(0, 18)]
 [DEBUG] embedding._create_projection: Calling _create_projection for subjects=['subj40', 'subj41', 'subj42', 'subj50', 'subj65', 'subj66', 'subj67', 'subj68'], features=('bh0', 'bh1', 'bh2', 'bh3', 'bh4', 'bh5', 'bh6', 'bh7', 'bh8', 'bh9', 'bh10', 'bh11', 'bh12', 'bh13', 'bh14', 'bh15', 'bh16', 'bh17', 'bh18'), and kwargs={'features_int': (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18)}
 [DEBUG] embedding.clone: Setting subjects_int to [40, 41, 42, 50, 65, 66, 67, 68]
 [DEBUG] embedding.project: Calling project for subjects=all and features=[('pc0', 'pc4')], heatmap=None, fvector=None, fbands=[], factory=None
 [DEBUG] mixins.wrapper: Calling _create_projection with stacklevel=2
 [DEBUG] mixins.wrapper: wrapper of process_subjects called with subjs=all, args=() and kwargs={'features': [('pc0', 'pc4')]}
 [DEBUG] mixins.wrapper: Getting subjects_int from self.subjects: ['subj40', 'subj41', 'subj42', 'subj50', 'subj65', 'subj66', 'subj67', 'subj68']
 [DEBUG] mixins.wrapper: Taking all subjects: [40, 41, 42, 50, 65, 66, 67, 68]
 [DEBUG] mixins.wrapper: Calling: _create_projection with subjs=[40, 41, 42, 50, 65, 66, 67, 68] and args=() and kwargs={'features': [('pc0', 'pc4')]}
 [DEBUG] mixins.wrapper: Calling _create_projection with subjs=[40, 41, 42, 50, 65, 66, 67, 68] and args=() and kwargs={'features': [('pc0', 'pc4')]}
 [DEBUG] mixins.wrapper: Processing features [('pc0', 'pc4')], heatmap None, fvector None, args=(['subj40', 'subj41', 'subj42', 'subj50', 'subj65', 'subj66', 'subj67', 'subj68'],), and kwargs={}
 [DEBUG] mixins.wrapper: PCA features detected, features: [(0, 4)]
 [DEBUG] mixins.wrapper: Validating feature: [(0, 4)]
 [DEBUG] mixins.validate_grid: Vallidating grid: [(0, 4)] and maxsize: 5
 [DEBUG] mixins.validate_grid: Vallidated grid: [0, 1, 2, 3, 4]
 [DEBUG] mixins.wrapper: valid_feature: [0, 1, 2, 3, 4]
 [DEBUG] mixins.wrapper: valid_features=[(0, 4)]
 [DEBUG] embedding._create_projection: Calling _create_projection for subjects=['subj40', 'subj41', 'subj42', 'subj50', 'subj65', 'subj66', 'subj67', 'subj68'], features=('pc0', 'pc1', 'pc2', 'pc3', 'pc4'), and kwargs={'features_int': (0, 1, 2, 3, 4)}
 [DEBUG] embedding.clone: Setting subjects_int to [40, 41, 42, 50, 65, 66, 67, 68]

#### `EmbeddingCollection` constructor and `Datasource.project` method create the same combined `EmbeddingCollection` object

In [ ]:
#| eval: false

combined_emb0.features

 [DEBUG] embedding.__getattr__: Accessing attribute/method 'features' across embeddings: found in ['pcomponents_ts', 'percentiles_ts', 'binheights_ts']

{'pcomponents_ts': ['pc0', 'pc1', 'pc2', 'pc3', 'pc4'],
 'percentiles_ts': ['p0',
  'p5',
  'p10',
  'p15',
  'p20',
  'p25',
  'p30',
  'p35',
  'p40',
  'p45',
  'p50',
  'p55',
  'p60',
  'p65',
  'p70',
  'p75',
  'p80',
  'p85',
  'p90',
  'p95',
  'p100'],
 'binheights_ts': ['bh0',
  'bh1',
  'bh2',
  'bh3',
  'bh4',
  'bh5',
  'bh6',
  'bh7',
  'bh8',
  'bh9',
  'bh10',
  'bh11',
  'bh12',
  'bh13',
  'bh14',
  'bh15',
  'bh16',
  'bh17',
  'bh18']}

In [ ]:
#| eval: false
combined_emb1.features

 [DEBUG] embedding.__getattr__: Accessing attribute/method 'features' across embeddings: found in ['percentiles_ts', 'binheights_ts', 'pcomponents_ts']

{'percentiles_ts': ('p0',
  'p5',
  'p10',
  'p15',
  'p20',
  'p25',
  'p30',
  'p35',
  'p40',
  'p45',
  'p50',
  'p55',
  'p60',
  'p65',
  'p70',
  'p75',
  'p80',
  'p85',
  'p90',
  'p95',
  'p100'),
 'binheights_ts': ('bh0',
  'bh1',
  'bh2',
  'bh3',
  'bh4',
  'bh5',
  'bh6',
  'bh7',
  'bh8',
  'bh9',
  'bh10',
  'bh11',
  'bh12',
  'bh13',
  'bh14',
  'bh15',
  'bh16',
  'bh17',
  'bh18'),
 'pcomponents_ts': ('pc0', 'pc1', 'pc2', 'pc3', 'pc4')}

In [ ]:
#| eval: false

combined_emb0.features_tint['subj40']['pcomponents_ts'] == combined_emb1.features_tint['subj40']['pcomponents_ts']

 [DEBUG] embedding.__getattr__: Accessing attribute/method 'features_tint' across embeddings: found in ['pcomponents_ts', 'percentiles_ts', 'binheights_ts']
 [DEBUG] embedding.__getattr__: Accessing attribute/method 'features_tint' across embeddings: found in ['percentiles_ts', 'binheights_ts', 'pcomponents_ts']

array([[ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True]])

In [ ]:
#| eval: false

combined_emb0.get_ts_subjs('pc1')['pcomponents_ts'] - combined_emb1.get_ts_subjs('pc1')['pcomponents_ts']

 [DEBUG] embedding.__getattr__: Accessing attribute/method 'get_ts_subjs' across embeddings: found in ['pcomponents_ts', 'percentiles_ts', 'binheights_ts']
 [DEBUG] embedding.get_ts_subjs: Getting time series for subjects for features pc1
 [DEBUG] embedding.get_ts_subjs: Available features: ['pc0', 'pc1', 'pc2', 'pc3', 'pc4']
 [DEBUG] embedding.get_ts_subjs: Getting time series for subjects for features pc1
 [DEBUG] embedding.get_ts_subjs: Available features: ['p0', 'p5', 'p10', 'p15', 'p20', 'p25', 'p30', 'p35', 'p40', 'p45', 'p50', 'p55', 'p60', 'p65', 'p70', 'p75', 'p80', 'p85', 'p90', 'p95', 'p100']
 [WARNING] embedding.get_ts_subjs_ftr: Feature pc1 not in features: ['p0', 'p5', 'p10', 'p15', 'p20', 'p25', 'p30', 'p35', 'p40', 'p45', 'p50', 'p55', 'p60', 'p65', 'p70', 'p75', 'p80', 'p85', 'p90', 'p95', 'p100']
 [DEBUG] embedding.get_ts_subjs: Getting time series for subjects for features pc1
 [DEBUG] embedding.get_ts_subjs: Available features: ['bh0', 'bh1', 'bh2', 'bh3', 'bh4', 'bh5', 'bh6', 'bh7', 'bh8', 'bh9', 'bh10', 'bh11', 'bh12', 'bh13', 'bh14', 'bh15', 'bh16', 'bh17', 'bh18']
 [WARNING] embedding.get_ts_subjs_ftr: Feature pc1 not in features: ['bh0', 'bh1', 'bh2', 'bh3', 'bh4', 'bh5', 'bh6', 'bh7', 'bh8', 'bh9', 'bh10', 'bh11', 'bh12', 'bh13', 'bh14', 'bh15', 'bh16', 'bh17', 'bh18']
 [DEBUG] embedding.__getattr__: Accessing attribute/method 'get_ts_subjs' across embeddings: found in ['percentiles_ts', 'binheights_ts', 'pcomponents_ts']
 [DEBUG] embedding.get_ts_subjs: Getting time series for subjects for features pc1
 [DEBUG] embedding.get_ts_subjs: Available features: ('p0', 'p5', 'p10', 'p15', 'p20', 'p25', 'p30', 'p35', 'p40', 'p45', 'p50', 'p55', 'p60', 'p65', 'p70', 'p75', 'p80', 'p85', 'p90', 'p95', 'p100')
 [WARNING] embedding.get_ts_subjs_ftr: Feature pc1 not in features: ('p0', 'p5', 'p10', 'p15', 'p20', 'p25', 'p30', 'p35', 'p40', 'p45', 'p50', 'p55', 'p60', 'p65', 'p70', 'p75', 'p80', 'p85', 'p90', 'p95', 'p100')
 [DEBUG] embedding.get_ts_subjs: Getting time series for subjects for features pc1
 [DEBUG] embedding.get_ts_subjs: Available features: ('bh0', 'bh1', 'bh2', 'bh3', 'bh4', 'bh5', 'bh6', 'bh7', 'bh8', 'bh9', 'bh10', 'bh11', 'bh12', 'bh13', 'bh14', 'bh15', 'bh16', 'bh17', 'bh18')
 [WARNING] embedding.get_ts_subjs_ftr: Feature pc1 not in features: ('bh0', 'bh1', 'bh2', 'bh3', 'bh4', 'bh5', 'bh6', 'bh7', 'bh8', 'bh9', 'bh10', 'bh11', 'bh12', 'bh13', 'bh14', 'bh15', 'bh16', 'bh17', 'bh18')
 [DEBUG] embedding.get_ts_subjs: Getting time series for subjects for features pc1
 [DEBUG] embedding.get_ts_subjs: Available features: ('pc0', 'pc1', 'pc2', 'pc3', 'pc4')

     subj40  subj41  subj42  subj50  subj65  subj66  subj67  subj68
0       0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0
1       0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0
2       0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0
3       0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0
4       0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0
..      ...     ...     ...     ...     ...     ...     ...     ...
995     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0
996     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0
997     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0
998     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0
999     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0

[1000 rows x 8 columns]

## Projected Embeddings
> only selected features are included in the embedding

In [ ]:
#| exports
#| eval: false

pca_emb_prj = pca_emb.project(         # project all available features of the Embedding pca_emb to specified `features`    
    subjs=[40],                        # specify subject(s) to project to: may be specified also as intervals, e.g., [(40, 45), 47]   
    features=['pc0', 'pc1'],           # specify features to project to: principal components are prefixed by 'pc', may be specified also as intervals, e.g., [('pc0', 'pc4')] 
)

percentile_emb_prj = percentile_emb.project(   # project all available features of the Embedding percentile_emb to specified `features`  
    subjs=[40],  
    features=['p0', 'p100'],           # percentiles are prefixed by 'p', may be specified also as intervals, e.g., [('p0', 'p20'), ('p80', 'p100')] 
)

bin_emb_prj = bin_emb.project(         # project all available features of the Embedding bin_emb to specified `features`     
    subjs=[40], 
    features=[('bh0', 'bh10')],        # bin heights are prefixed by 'bh': bins 1,2,..,10
)

 [DEBUG] embedding.project: Calling project for subjects=[40] and features=['pc0', 'pc1'], heatmap=None, fvector=None, fbands=None, factory=None
 [DEBUG] mixins.wrapper: Calling _create_projection with stacklevel=2
 [DEBUG] mixins.wrapper: wrapper of process_subjects called with subjs=[40], args=() and kwargs={'features': ['pc0', 'pc1']}
 [DEBUG] mixins.wrapper: Using self.subjects_int: [40, 41, 42, 50, 65, 66, 67, 68]
 [DEBUG] mixins.wrapper: Calling: _create_projection with subjs=[40] and args=() and kwargs={'features': ['pc0', 'pc1']}
 [DEBUG] mixins.wrapper: Calling _create_projection with subjs=[40] and args=() and kwargs={'features': ['pc0', 'pc1']}
 [DEBUG] mixins.wrapper: Processing features ['pc0', 'pc1'], heatmap None, fvector None, args=(['subj40'],), and kwargs={}
 [DEBUG] mixins.wrapper: PCA features detected, features: [0, 1]
 [DEBUG] mixins.wrapper: Validating feature: [0, 1]
 [DEBUG] mixins.validate_grid: Vallidating grid: [0, 1] and maxsize: 5
 [DEBUG] mixins.validate_grid: Vallidated grid: [0, 1]
 [DEBUG] mixins.wrapper: valid_feature: [0, 1]
 [DEBUG] mixins.wrapper: valid_features=[(0, 1)]
 [DEBUG] embedding._create_projection: Calling _create_projection for subjects=['subj40'], features=('pc0', 'pc1'), and kwargs={'features_int': (0, 1)}
 [DEBUG] embedding.clone: Setting subjects_int to [40]
 [DEBUG] embedding.project: Calling project for subjects=[40] and features=['p0', 'p100'], heatmap=None, fvector=None, fbands=None, factory=None
 [DEBUG] mixins.wrapper: Calling _create_projection with stacklevel=2
 [DEBUG] mixins.wrapper: wrapper of process_subjects called with subjs=[40], args=() and kwargs={'features': ['p0', 'p100']}
 [DEBUG] mixins.wrapper: Using self.subjects_int: [40, 41, 42, 50, 65, 66, 67, 68]
 [DEBUG] mixins.wrapper: Calling: _create_projection with subjs=[40] and args=() and kwargs={'features': ['p0', 'p100']}
 [DEBUG] mixins.wrapper: Calling _create_projection with subjs=[40] and args=() and kwargs={'features': ['p0', 'p100']}
 [DEBUG] mixins.wrapper: Processing features ['p0', 'p100'], heatmap None, fvector None, args=(['subj40'],), and kwargs={}
 [DEBUG] mixins.wrapper: Percentile features detected, after preprocessing: [0, 20]
 [DEBUG] mixins.wrapper: Validating feature: [0, 20]
 [DEBUG] mixins.validate_grid: Vallidating grid: [0, 20] and maxsize: 21
 [DEBUG] mixins.validate_grid: Vallidated grid: [0, 20]
 [DEBUG] mixins.wrapper: valid_feature: [0, 20]
 [DEBUG] mixins.wrapper: valid_features=[0, 20]
 [DEBUG] embedding._create_projection: Calling _create_projection for subjects=['subj40'], features=('p0', 'p100'), and kwargs={'features_int': (0, 20)}
 [DEBUG] embedding.clone: Setting subjects_int to [40]
 [DEBUG] embedding.project: Calling project for subjects=[40] and features=[('bh0', 'bh10')], heatmap=None, fvector=None, fbands=None, factory=None
 [DEBUG] mixins.wrapper: Calling _create_projection with stacklevel=2
 [DEBUG] mixins.wrapper: wrapper of process_subjects called with subjs=[40], args=() and kwargs={'features': [('bh0', 'bh10')]}
 [DEBUG] mixins.wrapper: Using self.subjects_int: [40, 41, 42, 50, 65, 66, 67, 68]
 [DEBUG] mixins.wrapper: Calling: _create_projection with subjs=[40] and args=() and kwargs={'features': [('bh0', 'bh10')]}
 [DEBUG] mixins.wrapper: Calling _create_projection with subjs=[40] and args=() and kwargs={'features': [('bh0', 'bh10')]}
 [DEBUG] mixins.wrapper: Processing features [('bh0', 'bh10')], heatmap None, fvector None, args=(['subj40'],), and kwargs={}
 [DEBUG] mixins.wrapper: Binheight features detected, features: [(0, 10)]
 [DEBUG] mixins.wrapper: Validating feature: [(0, 10)]
 [DEBUG] mixins.validate_grid: Vallidating grid: [(0, 10)] and maxsize: 19
 [DEBUG] mixins.validate_grid: Vallidated grid: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
 [DEBUG] mixins.wrapper: valid_feature: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
 [DEBUG] mixins.wrapper: valid_features=[(0, 10)]
 [DEBUG] embedding._create_projection: Calling _create_projection for subjects=['subj40'], features=('bh0', 'bh1', 'bh2', 'bh3', 'bh4', 'bh5', 'bh6', 'bh7', 'bh8', 'bh9', 'bh10'), and kwargs={'features_int': (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10)}
 [DEBUG] embedding.clone: Setting subjects_int to [40]

### Combine projected embeddings

#### `EmbeddingCollection` constructor

In [ ]:
#| exports
#| eval: false

combined_emb0_prj = EmbeddingCollection(pca_emb_prj, percentile_emb_prj, bin_emb_prj)

#### `Datasource.project` syntactic shorthand

In [ ]:
#| exports
#| eval: false

combined_emb1_prj = dg0.face_t.project(       # project all available features of the Datasource face_t to specified `features`  
    subjs=[40],                               # specify subject(s) to project to: may be specified also as intervals, e.g., [(40, 45), 47] 
    features=['pc0', 'pc1', 'p0', 'p100', ('bh0', 'bh10')],  # specify features to project to: principal components 'pc', percentiles 'p', bin heights 'bh'   
    pcfactory=pca,                            # specify PCA for principle components
)

 [DEBUG] piece.project: Calling BaseDatasource.project with subjs=[40], features=['pc0', 'pc1', 'p0', 'p100', ('bh0', 'bh10')], heatmap=None, fvector=None, fbands=None, pcfactory=<fhemb.utils.factories.ConcretePcaFactory object>, wdfactory=None
 [DEBUG] piece._choose_embedding: Classified features: {'percentiles': ['p0', 'p100'], 'bins': [('bh0', 'bh10')], 'pcomponents': ['pc0', 'pc1'], 'stat_features': []}
 [DEBUG] piece._choose_embedding: classified percentiles: ['p0', 'p100']
 [DEBUG] piece._choose_embedding: classified bins: [('bh0', 'bh10')]
 [DEBUG] piece._choose_embedding: classified pcomponents: ['pc0', 'pc1']
 [DEBUG] piece.create_pca_embedding: Calling create_pca_embedding
 [DEBUG] tutils.create: Creating create_pca_embedding with args: StandardScaler(copy=True,with_mean=True,with_std=False) | KernelPCA(alpha=1.0,coef0=1,copy_X=True,degree=3,eigen_solver='auto',fit_inverse_transform=True,gamma=0.07,iterated_power='auto',kernel='sigmoid',kernel_params=None,max_iter=None,n_components=5,n_jobs=None,random_state=None,remove_zero_eig=False,tol=0) and kwargs: dict_keys(['factory', 'datasource', 'subjects', 'time_interval', 'temperature_threshold'])
 [DEBUG] tutils.create: Using already calculated value for StandardScaler(copy=True,with_mean=True,with_std=False) | KernelPCA(alpha=1.0,coef0=1,copy_X=True,degree=3,eigen_solver='auto',fit_inverse_transform=True,gamma=0.07,iterated_power='auto',kernel='sigmoid',kernel_params=None,max_iter=None,n_components=5,n_jobs=None,random_state=None,remove_zero_eig=False,tol=0)
 [DEBUG] piece.project: Chosen embeddings: [('percentiles_ts', {'embedding': <fhemb.embedding.Embedding object>, 'features': ['p0', 'p100']}), ('binheights_ts', {'embedding': <fhemb.embedding.Embedding object>, 'features': [('bh0', 'bh10')]}), ('pcomponents_ts', {'embedding': <fhemb.embedding.Embedding object>, 'features': ['pc0', 'pc1']})]
 [DEBUG] embedding.project: Calling project for subjects=[40] and features=['p0', 'p100'], heatmap=None, fvector=None, fbands=[], factory=None
 [DEBUG] mixins.wrapper: Calling _create_projection with stacklevel=2
 [DEBUG] mixins.wrapper: wrapper of process_subjects called with subjs=[40], args=() and kwargs={'features': ['p0', 'p100']}
 [DEBUG] mixins.wrapper: Using self.subjects_int: [40, 41, 42, 50, 65, 66, 67, 68]
 [DEBUG] mixins.wrapper: Calling: _create_projection with subjs=[40] and args=() and kwargs={'features': ['p0', 'p100']}
 [DEBUG] mixins.wrapper: Calling _create_projection with subjs=[40] and args=() and kwargs={'features': ['p0', 'p100']}
 [DEBUG] mixins.wrapper: Processing features ['p0', 'p100'], heatmap None, fvector None, args=(['subj40'],), and kwargs={}
 [DEBUG] mixins.wrapper: Percentile features detected, after preprocessing: [0, 20]
 [DEBUG] mixins.wrapper: Validating feature: [0, 20]
 [DEBUG] mixins.validate_grid: Vallidating grid: [0, 20] and maxsize: 21
 [DEBUG] mixins.validate_grid: Vallidated grid: [0, 20]
 [DEBUG] mixins.wrapper: valid_feature: [0, 20]
 [DEBUG] mixins.wrapper: valid_features=[0, 20]
 [DEBUG] embedding._create_projection: Calling _create_projection for subjects=['subj40'], features=('p0', 'p100'), and kwargs={'features_int': (0, 20)}
 [DEBUG] embedding.clone: Setting subjects_int to [40]
 [DEBUG] embedding.project: Calling project for subjects=[40] and features=[('bh0', 'bh10')], heatmap=None, fvector=None, fbands=[], factory=None
 [DEBUG] mixins.wrapper: Calling _create_projection with stacklevel=2
 [DEBUG] mixins.wrapper: wrapper of process_subjects called with subjs=[40], args=() and kwargs={'features': [('bh0', 'bh10')]}
 [DEBUG] mixins.wrapper: Using self.subjects_int: [40, 41, 42, 50, 65, 66, 67, 68]
 [DEBUG] mixins.wrapper: Calling: _create_projection with subjs=[40] and args=() and kwargs={'features': [('bh0', 'bh10')]}
 [DEBUG] mixins.wrapper: Calling _create_projection with subjs=[40] and args=() and kwargs={'features': [('bh0', 'bh10')]}
 [DEBUG] mixins.wrapper: Processing features [('bh0', 'bh10')], heatmap None, fvector None, args=(['subj40'],), and kwargs={}
 [DEBUG] mixins.wrapper: Binheight features detected, features: [(0, 10)]
 [DEBUG] mixins.wrapper: Validating feature: [(0, 10)]
 [DEBUG] mixins.validate_grid: Vallidating grid: [(0, 10)] and maxsize: 19
 [DEBUG] mixins.validate_grid: Vallidated grid: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
 [DEBUG] mixins.wrapper: valid_feature: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
 [DEBUG] mixins.wrapper: valid_features=[(0, 10)]
 [DEBUG] embedding._create_projection: Calling _create_projection for subjects=['subj40'], features=('bh0', 'bh1', 'bh2', 'bh3', 'bh4', 'bh5', 'bh6', 'bh7', 'bh8', 'bh9', 'bh10'), and kwargs={'features_int': (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10)}
 [DEBUG] embedding.clone: Setting subjects_int to [40]
 [DEBUG] embedding.project: Calling project for subjects=[40] and features=['pc0', 'pc1'], heatmap=None, fvector=None, fbands=[], factory=None
 [DEBUG] mixins.wrapper: Calling _create_projection with stacklevel=2
 [DEBUG] mixins.wrapper: wrapper of process_subjects called with subjs=[40], args=() and kwargs={'features': ['pc0', 'pc1']}
 [DEBUG] mixins.wrapper: Using self.subjects_int: [40, 41, 42, 50, 65, 66, 67, 68]
 [DEBUG] mixins.wrapper: Calling: _create_projection with subjs=[40] and args=() and kwargs={'features': ['pc0', 'pc1']}
 [DEBUG] mixins.wrapper: Calling _create_projection with subjs=[40] and args=() and kwargs={'features': ['pc0', 'pc1']}
 [DEBUG] mixins.wrapper: Processing features ['pc0', 'pc1'], heatmap None, fvector None, args=(['subj40'],), and kwargs={}
 [DEBUG] mixins.wrapper: PCA features detected, features: [0, 1]
 [DEBUG] mixins.wrapper: Validating feature: [0, 1]
 [DEBUG] mixins.validate_grid: Vallidating grid: [0, 1] and maxsize: 5
 [DEBUG] mixins.validate_grid: Vallidated grid: [0, 1]
 [DEBUG] mixins.wrapper: valid_feature: [0, 1]
 [DEBUG] mixins.wrapper: valid_features=[(0, 1)]
 [DEBUG] embedding._create_projection: Calling _create_projection for subjects=['subj40'], features=('pc0', 'pc1'), and kwargs={'features_int': (0, 1)}
 [DEBUG] embedding.clone: Setting subjects_int to [40]

#### `EmbeddingCollection` and `Datasource.project` create the same combined `Embedding`

In [ ]:
#| eval: false

combined_emb0_prj.features

 [DEBUG] embedding.__getattr__: Accessing attribute/method 'features' across embeddings: found in ['pcomponents_ts', 'percentiles_ts', 'binheights_ts']

{'pcomponents_ts': ('pc0', 'pc1'),
 'percentiles_ts': ('p0', 'p100'),
 'binheights_ts': ('bh0',
  'bh1',
  'bh2',
  'bh3',
  'bh4',
  'bh5',
  'bh6',
  'bh7',
  'bh8',
  'bh9',
  'bh10')}

In [ ]:
#| eval: false

combined_emb1_prj.features

 [DEBUG] embedding.__getattr__: Accessing attribute/method 'features' across embeddings: found in ['percentiles_ts', 'binheights_ts', 'pcomponents_ts']

{'percentiles_ts': ('p0', 'p100'),
 'binheights_ts': ('bh0',
  'bh1',
  'bh2',
  'bh3',
  'bh4',
  'bh5',
  'bh6',
  'bh7',
  'bh8',
  'bh9',
  'bh10'),
 'pcomponents_ts': ('pc0', 'pc1')}

In [ ]:
#| eval: false

combined_emb0_prj.features_tint['subj40']['percentiles_ts']

 [DEBUG] embedding.__getattr__: Accessing attribute/method 'features_tint' across embeddings: found in ['pcomponents_ts', 'percentiles_ts', 'binheights_ts']

array([[28.81271744, 28.39035416, 28.44665527, ..., 28.25575829,
        28.08575058, 27.8315239 ],
       [32.73644257, 32.69075012, 32.75925827, ..., 32.73644257,
        32.72121811, 32.70979691]])

In [ ]:
#| eval: false

combined_emb0_prj.features_tint['subj40']['pcomponents_ts'] == combined_emb1_prj.features_tint['subj40']['pcomponents_ts']

 [DEBUG] embedding.__getattr__: Accessing attribute/method 'features_tint' across embeddings: found in ['pcomponents_ts', 'percentiles_ts', 'binheights_ts']
 [DEBUG] embedding.__getattr__: Accessing attribute/method 'features_tint' across embeddings: found in ['percentiles_ts', 'binheights_ts', 'pcomponents_ts']

array([[ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True]])

In [ ]:
#| eval: false

combined_emb1_prj.get_ts_subjs('bh5')['binheights_ts'] - combined_emb1_prj.get_ts_subjs('bh5')['binheights_ts']

 [DEBUG] embedding.__getattr__: Accessing attribute/method 'get_ts_subjs' across embeddings: found in ['percentiles_ts', 'binheights_ts', 'pcomponents_ts']
 [DEBUG] embedding.get_ts_subjs: Getting time series for subjects for features bh5
 [DEBUG] embedding.get_ts_subjs: Available features: ('p0', 'p100')
 [WARNING] embedding.get_ts_subjs_ftr: Feature bh5 not in features: ('p0', 'p100')
 [DEBUG] embedding.get_ts_subjs: Getting time series for subjects for features bh5
 [DEBUG] embedding.get_ts_subjs: Available features: ('bh0', 'bh1', 'bh2', 'bh3', 'bh4', 'bh5', 'bh6', 'bh7', 'bh8', 'bh9', 'bh10')
 [DEBUG] embedding.get_ts_subjs: Getting time series for subjects for features bh5
 [DEBUG] embedding.get_ts_subjs: Available features: ('pc0', 'pc1')
 [WARNING] embedding.get_ts_subjs_ftr: Feature bh5 not in features: ('pc0', 'pc1')
 [DEBUG] embedding.__getattr__: Accessing attribute/method 'get_ts_subjs' across embeddings: found in ['percentiles_ts', 'binheights_ts', 'pcomponents_ts']
 [DEBUG] embedding.get_ts_subjs: Getting time series for subjects for features bh5
 [DEBUG] embedding.get_ts_subjs: Available features: ('p0', 'p100')
 [WARNING] embedding.get_ts_subjs_ftr: Feature bh5 not in features: ('p0', 'p100')
 [DEBUG] embedding.get_ts_subjs: Getting time series for subjects for features bh5
 [DEBUG] embedding.get_ts_subjs: Available features: ('bh0', 'bh1', 'bh2', 'bh3', 'bh4', 'bh5', 'bh6', 'bh7', 'bh8', 'bh9', 'bh10')
 [DEBUG] embedding.get_ts_subjs: Getting time series for subjects for features bh5
 [DEBUG] embedding.get_ts_subjs: Available features: ('pc0', 'pc1')
 [WARNING] embedding.get_ts_subjs_ftr: Feature bh5 not in features: ('pc0', 'pc1')

     subj40
0       0.0
1       0.0
2       0.0
3       0.0
4       0.0
..      ...
995     0.0
996     0.0
997     0.0
998     0.0
999     0.0

[1000 rows x 1 columns]